[workspace]

resolver = "2"

members = [
    "examples/example-001",
    "examples/example-002"
    , "examples/example-003", "examples/example-004", "examples/example-005"]

[workspace.package]
version = "0.0.0"
authors = ["Dariusz Depta <depta@engos.de>"]
repository = "https://github.com/EngosSoftware/cli-assert-examples.git"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[workspace.dependencies]
cli-assert = "0.1.1"
